#!/usr/bin/env ruby

# Generates the mapping properties between XML tag names and their corresponding Java class names.
#
# @ernest.micklei@philemonworks.com
#
File.open('src/main/resources/task-mapping.properties' , 'w') do |mapping|
	mapping << "# generated by task-mapping.rb on #{Time.now}\n"
	javafiles = File.join("**", "src/main/java/com/philemonworks/selfdiagnose/check", "**", "*.java")
	Dir.glob(javafiles) { |each|
		qname = each[14..each.length-6].gsub('/','.')
		clsname = qname.split('.').last
		mapping << "#{clsname.downcase}=#{qname}\n"
	}
	
	javafiles = File.join("**", "src/main/java/com/philemonworks/selfdiagnose/report", "**", "*.java")
	Dir.glob(javafiles) { |each|
		qname = each[14..each.length-6].gsub('/','.')
		clsname = qname.split('.').last
		mapping << "#{clsname.downcase}=#{qname}\n"
	}	
end